// todo-mvc/react/components/Header.jsx
import React, { Component, PropTypes} from 'react';
import TodoInput from './TodoInput.jsx'

class Header extends Component {
  constructor(props) {
    super(props);
  }

  static propTypes = {
    addTodo: PropTypes.func.isRequired
  }

  addHandler = (text) => {
    if (text.length) {
      this.props.addTodo(text);
    }
  }

  render = () => {
    return (
      <header className="header">
        <h1>todos</h1>
        <TodoInput onUpdate={this.addHandler.bind(this)} placeholder="What needs to be done?"></TodoInput>
      </header>
    );
  }
}

export default Header;

// todo-mvc/vue/src/modules/TodoList/components/Header/Header.vue
<template>
  <header class="header">
    <h1>todos</h1>
    <todo-input placeholder="What needs to be done?" is-create ></todo-input>
  </header>
</template>

<script>
  import TodoInput from '../TodoInput/TodoInput'
  import LocalStorageUtil from 'LocalStorageUtil'

  export default {
    components: { TodoInput }
    methods: {
      addItem: function (text) {

      }
    }
  }
</script>
